name: Flutter_Tests

on:
  pull_request:
    branches: [main, develop]

jobs:
  flutter_test:
    env: 
      working-directory: ./app
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    name: Run Flutter Acceptance Tests and Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Setup Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 31
        profile: Nexus 6
        arch: arm64-v8a
        force-avd-creation: false
        avd-name: avd-arm64-v8a-31
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        script: ./gradlew connectedCheck
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter test --coverage -x ignore
