name: Flutter_Tests

on:
  pull_request:
    branches: [main, develop]

jobs:
  flutter_test:
    env: 
      working-directory: ./app
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    name: Run Flutter Acceptance Tests and Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Start emulator
      run: |
        sdkmanager --list || true
        echo y | sdkmanager "system-images;android-29;google_apis;x86_64"
        echo no | avdmanager create avd -n test -k "system-images;android-29;google_apis;x86_64" --force
        emulator -avd test -no-audio -no-window &
        android-wait-for-emulator
        adb shell input keyevent 82 &
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter test --coverage -x ignore --device-id emulator-5554
